[package]
name = "package_and_crate"
version = "0.1.0"
edition = "2021"
default-run = "package_and_crate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "daemon"
path = "src/daemon/bin/main.rs"
